FORBIDDEN_COLS = {
    "DEPARTURE_DELAY", "DEPARTURE_TIME", "TAXI_OUT", "WHEELS_OFF",
    "WHEELS_ON", "TAXI_IN", "AIR_TIME", "ELAPSED_TIME", "ARRIVAL_TIME",
    "AIR_SYSTEM_DELAY", "SECURITY_DELAY", "AIRLINE_DELAY",
    "LATE_AIRCRAFT_DELAY", "WEATHER_DELAY",
}

FEATURES = ["AIRLINE", "ORIGIN_AIRPORT", "DESTINATION_AIRPORT", "DAY_OF_WEEK", "DEP_HOUR"]